# TensorFlow operations

This jupyter notebook contains many cells with basic examples to TensorFlow operations.

In [2]:
import tensorflow as tf

Lets first look at [Constants, Sequences, and Random Values](https://www.tensorflow.org/versions/r0.8/api_docs/python/constant_op.html)

In [2]:
a = tf.zeros((3, 3), dtype=tf.float32, name=None)
b = tf.zeros_like(a, dtype=None, name=None)
c = tf.ones((2, 2), dtype=tf.float32, name=None)
d = tf.ones_like(c, dtype=None, name=None)
e = tf.fill((2,1), 3.140, name=None)
f = tf.constant([12,2], dtype=tf.int32, name=None)

In [3]:
sess = tf.Session()
with sess.as_default():
    print 'tf.zeroes'
    print a.eval()
    print 'tf.zeroes_like'
    print b.eval()
    print 'tf.ones'
    print c.eval() 
    print'tf.ones_like'
    print d.eval()
    print 'tf.fill'
    print e.eval()
    print 'tf.constant'
    print f.eval()
sess.close()

tf.zeroes
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
tf.zeroes_like
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
tf.ones
[[ 1.  1.]
 [ 1.  1.]]
tf.ones_like
[[ 1.  1.]
 [ 1.  1.]]
tf.fill
[[ 3.1400001]
 [ 3.1400001]]
tf.constant
[12  2]


In [4]:
#another way of printing TensorFlow is like this 
sess = tf.InteractiveSession()
print sess.run(a)
print sess.run(b)
print sess.run(c)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.]
 [ 1.  1.]]


In [5]:
a = tf.linspace(0.0, 10.0, 10, name="linspace")
b = tf.linspace(0.0, 12.4, 7, name="linspace")
sess = tf.Session()
with sess.as_default():
    print 'tf.linspace'
    print a.eval()
    print b.eval()

tf.linspace
[  0.           1.11111116   2.22222233   3.33333349   4.44444466
   5.55555582   6.66666698   7.77777815   8.88888931  10.        ]
[  0.           2.0666666    4.13333321   6.19999981   8.26666641
  10.33333302  12.39999962]


In [6]:
# tf.range is for integers 
a = tf.range(4, limit=15, delta=3, name='range')
with sess.as_default():
    print 'tf.range'
    print a.eval()

tf.range
[ 4  7 10 13]


In [7]:
# Create a tensor of shape [2, 3] consisting of random normal values, with mean
# -1 and standard deviation 4.
norm = tf.random_normal([2, 3], mean=-1, stddev=4)
with sess.as_default():
    print 'tf.random_normal'
    print norm.eval()

tf.random_normal
[[-3.50035119  0.77889049 -8.97565269]
 [ 1.58909321 -0.27798051 -1.16660023]]


In [8]:
# Shuffle the first dimension of a tensor
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)
with sess.as_default():
    print 'tf.shuffle'
    print shuff.eval()
    print 'tf.shuffle second time'
    print shuff.eval()

tf.shuffle
[[3 4]
 [5 6]
 [1 2]]
tf.shuffle second time
[[5 6]
 [1 2]
 [3 4]]


In [9]:
a= tf.random_normal((2,6), mean=0.2, stddev=1.0, seed=None, name='Norm')
print sess.run(a)
print sess.run(a)

[[ 1.35836506  1.67446887 -0.11730157  1.89177263 -0.26672947 -0.09724663]
 [ 0.57759356  2.3977263  -0.89397496 -0.69276673  0.37279084 -0.07325853]]
[[ 0.05119526 -1.6910634   0.42184353  2.23443246 -0.01840109 -3.61234474]
 [-0.33577418 -0.12074886 -0.87402958  0.20901743  2.40554023  0.97906017]]


In [10]:
tf.set_random_seed(1234)
a = tf.random_normal((1,1), mean=0.2, stddev=1.0, name='Norm')
with sess.as_default():
    print a.eval()
    print a.eval()
with tf.Session() as sess1:
    print a.eval()
    print a.eval()

[[ 0.4357354]]
[[-0.67853993]]
[[ 0.4357354]]
[[-0.67853993]]


In [11]:
tf.set_random_seed(1234)
a = tf.random_uniform([1], seed=4321)
b = tf.random_normal([1],  seed=4321)

# Repeatedly running this block with the same graph will generate different
# sequences of 'a' and 'b'.
print("Session 1")
with tf.Session() as sess1:
    print(sess1.run(a))  # generates 'A1'
    print(sess1.run(a))  # generates 'A2'
    print(sess1.run(b))  # generates 'B1'
    print(sess1.run(b))  # generates 'B2'

print("Session 2")
with tf.Session() as sess2:
    print(sess2.run(a))  # generates 'A1'
    print(sess2.run(a))  # generates 'A2'
    print(sess2.run(b))  # generates 'B1'
    print(sess2.run(b))  # generates 'B2'

Session 1
[ 0.46764243]
[ 0.15858293]
[ 1.22556162]
[-1.55450916]
Session 2
[ 0.46764243]
[ 0.15858293]
[ 1.22556162]
[-1.55450916]


In [12]:
#tf.set_random_seed(1234)
a = tf.random_uniform([1], seed= 1234)
b = tf.random_normal([1])

# Repeatedly running this block with the same graph will generate different
# sequences of 'a' and 'b'.
print("Session 1")
with tf.Session() as sess1:
    print(sess1.run(a))  # generates 'A1'
    print(sess1.run(a))  # generates 'A2'
    print(sess1.run(b))  # generates 'B1'
    print(sess1.run(b))  # generates 'B2'

print("Session 2")
with tf.Session() as sess2:
    print(sess2.run(a))  # generates 'A1'
    print(sess2.run(a))  # generates 'A2'
    print(sess2.run(b))  # generates 'B1'
    print(sess2.run(b))  # generates 'B2'

Session 1
[ 0.73822105]
[ 0.20240712]
[ 0.17799301]
[ 0.45085534]
Session 2
[ 0.73822105]
[ 0.20240712]
[ 0.17799301]
[ 0.45085534]


In [5]:
a = tf.ones([2,2])
print(a)


Tensor("ones_1:0", shape=(2, 2), dtype=float32)


ValueError: Cannot evaluate tensor using eval(): No default session is registered. Use `with sess.as_default()` or pass an explicit session to eval(session=sess)