# TensorFlow Basics

In this notebook we will cover some of the TF basics

See https://www.youtube.com/watch?v=L8Y2_Cq2X5s&feature=youtu.be for lecture

Website : http://cs224d.stanford.edu/

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

/Users/Christopher_old/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/Christopher_old/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))


## Basics 

In [2]:
import tensorflow as tf
tf.InteractiveSession()

In [3]:
a = tf.ones([2,2])
print a
a.eval()

Tensor("ones:0", shape=(2, 2), dtype=float32)


array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

## All evalutaion is done in context of a session

In [8]:
with tf.Session() as sess:
    print sess.run(a)
    print a.eval()

[[ 1.  1.]
 [ 1.  1.]]
[[ 1.  1.]
 [ 1.  1.]]


## Variables first class citizen in TensorFlow

In [11]:
var = tf.Variable(tf.zeros([2,2]), name='var')
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print var.eval()

[[ 0.  0.]
 [ 0.  0.]]


In [12]:
### variables cn be updated  
state = tf.Variable(0, name="counter")
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value)
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


## How to insert values in the computational graph

In [13]:
input1 = tf.constant(3.0)
input2 = tf.constant(2.0)
input3 = tf.constant(5.0)
intermed = tf.add(input2, input3)
mul = tf.mul(input1, intermed)
with tf.Session() as sess:
    result = sess.run([mul, intermed])
    print(result)

[21.0, 7.0]


# convert numpy to tensorflow

In [14]:
a = np.zeros((3,3))
ta = tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(ta))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


# use place holder and feed_dict

In [15]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.mul(input1, input2)
with tf.Session() as sess:
    print(sess.run([output], feed_dict={input1:[14], input2:[3]}))
    print(sess.run([output], feed_dict={input1:[209], input2:[44]}))
    print(sess.run([output], feed_dict={input1:[-9.5], input2:[1]}))

[array([ 42.], dtype=float32)]
[array([ 9196.], dtype=float32)]
[array([-9.5], dtype=float32)]


In [16]:
input1 = tf.placeholder(tf.float32, shape=[2])
input2 = tf.placeholder(tf.float32, shape=[2])
output = tf.mul(input1, input2)
with tf.Session() as sess:
    print(sess.run([output], feed_dict={input1:np.array([14,4]), input2:np.array([3,5])}))
    print(sess.run([output], feed_dict={input1:np.array([54,12]), input2:np.array([-7,34])}))

[array([ 42.,  20.], dtype=float32)]
[array([-378.,  408.], dtype=float32)]


# scope and get_variable 

In [17]:
with tf.variable_scope("foo"):
    with tf.variable_scope("bar"):
        v = tf.get_variable("v", [1])
assert v.name == "foo/bar/v:0"
print v.name

foo/bar/v:0


In [18]:
with tf.variable_scope("foo"):
    b = tf.get_variable("b", [1])
    tf.get_variable_scope().reuse_variables()
    b1 = tf.get_variable("b", [1])
assert b1 == b
print b1 == b

True


In [19]:
with tf.variable_scope("foo"):
    c = tf.get_variable("c", [1])
    c1 = tf.get_variable("c", [1])
assert c1 == c
print c1 == c

ValueError: Variable foo/c already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "<ipython-input-19-a4a74228bde8>", line 2, in <module>
    c = tf.get_variable("c", [1])
  File "/Users/Christopher_old/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/Users/Christopher_old/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3006, in run_ast_nodes
    if self.run_code(code, result):
